name: test_inferelator_prior
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bedtools=2.30.0
  - ghostscript=9.18
  - meme=5.4.1
  - ncbi-ngs-sdk=2.11.2
  - perl=5.32.1
  - perl-base=2.23
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.38
  - perl-cgi=4.54
  - perl-common-sense=3.75
  - perl-compress-raw-zlib=2.101
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-dbi=1.643
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.58
  - perl-encode=3.16
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.64
  - perl-file-listing=6.14
  - perl-file-path=2.18
  - perl-file-spec=3.48_01
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-template=2.97
  - perl-html-tree=5.07
  - perl-http-cookies=6.10
  - perl-http-daemon=6.13
  - perl-http-date=6.05
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.074
  - perl-json=4.05
  - perl-json-xs=2.34
  - perl-libwww-perl=6.61
  - perl-log-log4perl=1.54
  - perl-lwp-mediatypes=6.04
  - perl-math-cdf=0.1
  - perl-mime-base64=3.16
  - perl-net-http=6.22
  - perl-net-ssleay=1.92
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-scalar-list-utils=1.61
  - perl-socket=2.027
  - perl-threaded=5.32.1
  - perl-time-local=1.30
  - perl-timedate=2.33
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-uri=5.10
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-yaml=1.30
  - samtools=1.15
  - sra-tools=2.11.0
  - star=2.7.10a
