# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Inferelator-Prior CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: test-environment.yml
        activate-environment: test_inferelator_prior
        auto-activate-base: false
    - name: Conda Info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda env list
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install Cython --install-option="--no-cython-compile"
        python -m pip install coverage pytest
        python -m pip install numpy matplotlib pysam anndata scanpy
        python -m pip install -r requirements.txt
    - name: Test with pytest & coverage
      shell: bash -l {0}
      run: |
        python -m coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
