# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Inferelator-Prior CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test_inferelator_prior
        environment-file: test-environment.yml
        auto-activate-base: false
    - name: Conda Info
      run: |
        conda info
        conda list
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install Cython --install-option="--no-cython-compile"
        python -m pip install coverage pytest
        python -m pip install numpy matplotlib pysam
        python -m pip install -r requirements.txt
    - name: Test with pytest & coverage
      run: |
        python -m coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
